baseURL = ""
languageCode = "en-us"
title = "Naruto Senki - V2"
publishDir = "public"

[params]
    avatar = "img/avatar.svg"
    mainbg = "https://picsum.photos/1920/1080"
    name = "Re"
    mainTitle = "Naruto Senki - V2"
    mainText = "Android, Linux, Windows"
[menus]
    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "#projects"
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "#about"
    [[menu.main]]
        identifier = "help"
        name = "Help"
        url = "#help"
